export const SOLUTIONS = [
  {
    id: "technical-consulting",
    title: "Technical Consulting",
    tagline: "Expert guidance for every chemical challenge",
    icon: "FlaskConical",
    color: "from-blue-900 to-blue-800",
    desc: "Our team of chemical engineers and industry specialists work alongside your team to select the right products, optimise formulations, and solve process challenges — from raw material sourcing to final product compliance, with cost reduction and faster market entry.",
    features: [
      "Product selection & application support",
      "Formulation optimisation",
      "Regulatory & safety compliance guidance",
      "On-site technical assessments",
      "R&D collaboration for new product development",
      "Process troubleshooting & yield improvement",
    ],
  },
  {
    id: "quality-assurance",
    title: "Quality Assurance",
    tagline: "Certified quality from source to delivery",
    icon: "Trophy",
    color: "from-emerald-900 to-emerald-800",
    desc: "Every product we supply undergoes rigorous quality checks aligned with KEBS, ISO, GMP, and HACCP standards. Full traceability and documentation is included with every shipment — so you always know exactly what you're getting.",
    features: [
      "Full Certificate of Analysis (CoA) with every batch",
      "Safety Data Sheets (SDS) for all products",
      "KEBS, ISO & GMP compliant sourcing",
      "Third-party lab testing on request",
      "Lot traceability & documentation",
      "Food-grade and pharmaceutical-grade certification",
    ],
  },
  {
    id: "logistics-distribution",
    title: "Logistics & Distribution",
    tagline: "Reliable delivery across East Africa",
    icon: "Truck",
    color: "from-amber-900 to-amber-800",
    desc: "Our modern fleet and established distribution network delivers across Kenya and wider East Africa. Temperature-controlled and HAZMAT-compliant logistics ensure your chemicals arrive safely, on time, with full documentation.",
    features: [
      "Same-day and next-day delivery in Nairobi",
      "Upcountry and regional distribution",
      "Hazardous materials (HAZMAT) handling",
      "Temperature-controlled transport available",
      "Bulk tanker delivery for liquid chemicals",
      "Real-time shipment tracking",
    ],
  },
  {
    id: "supply-chain",
    title: "Supply Chain Management",
    tagline: "Streamlined procurement for your operation",
    icon: "Link2",
    color: "from-violet-900 to-violet-800",
    desc: "We function as your single-source chemical procurement partner — consolidating suppliers and managing inventory to reduce overhead and prevent shortages, backed by strategic stocking and global sourcing relationships across 20+ countries.",
    features: [
      "Single-source procurement for all chemical needs",
      "Vendor-managed inventory (VMI)",
      "Long-term supply agreements & blanket orders",
      "Import & customs clearance handling",
      "Global supplier network across 20+ countries",
      "Emergency supply & stock-out prevention",
    ],
  },
  {
    id: "custom-formulations",
    title: "Custom Formulations",
    tagline: "Bespoke chemical blends built for your needs",
    icon: "TestTubes",
    color: "from-rose-900 to-rose-800",
    desc: "Our formulation team develops custom chemical blends and specialty mixtures tailored to your exact specifications — from cleaning compounds and industrial degreasers to food-grade ingredient mixes — with full technical support throughout.",
    features: [
      "Custom blending & mixing services",
      "Private label packaging available",
      "Small-batch pilot runs to full production",
      "Stability and compatibility testing",
      "Food, pharma & industrial grade options",
      "NDA-protected proprietary formulation development",
    ],
  },
];

export const NAV_SOLUTIONS = [
  { label: "Technical Consulting",    href: "/solutions#technical-consulting" },
  { label: "Quality Assurance",       href: "/solutions#quality-assurance" },
  { label: "Logistics & Distribution", href: "/solutions#logistics-distribution" },
  { label: "Supply Chain Management", href: "/solutions#supply-chain" },
  { label: "Custom Formulations",     href: "/solutions#custom-formulations" },
];

export const STATS = [
  { value: "1,000+", label: "Product Lines" },
  { value: "500+",   label: "Active Clients" },
  { value: "50+",    label: "Global Partners" },
  { value: "6+",     label: "Countries Served" },
];

export const DIVISIONS = [
  {
    id: "industrial",
    title: "Industrial Chemicals",
    icon: "Factory",
    color: "from-blue-900 to-blue-800",
    products: ["Caustic Soda (Flakes / Pearls)", "Sodium Hypochlorite", "Hydrochloric Acid", "Sulfuric Acid", "Nitric Acid", "Ammonia Solution", "Sodium Silicate", "Industrial Ethanol"],
  },
  {
    id: "food",
    title: "Food Processing Chemicals",
    icon: "Wheat",
    color: "from-emerald-900 to-emerald-800",
    products: ["Citric Acid Monohydrate", "Ascorbic Acid (Vitamin C)", "Sodium Benzoate", "Potassium Sorbate", "Acetic Acid (Food Grade)", "Lactic Acid", "Calcium Propionate", "Vitamin AD3"],
  },
  {
    id: "pharma",
    title: "Pharmaceutical Raw Materials",
    icon: "Pill",
    color: "from-violet-900 to-violet-800",
    products: ["Active Pharmaceutical Ingredients", "Excipients & Carriers", "Pharma-Grade Solvents", "Glycerin (Pharma Grade)", "Ethanol (Pharma Grade)", "Liquid Glucose", "Sorbitol Solution", "Microcrystalline Cellulose"],
  },
  {
    id: "petroleum",
    title: "Petroleum & Solvents",
    icon: "Droplets",
    color: "from-amber-900 to-amber-800",
    products: ["Solvent Naphtha", "Toluene", "Xylene", "Hexane", "White Spirit", "Isopropyl Alcohol", "Lubricant Additives", "Acetone"],
  },
  {
    id: "laboratory",
    title: "Laboratory Equipment",
    icon: "Microscope",
    color: "from-cyan-900 to-cyan-800",
    products: ["UV-VIS Spectrophotometers", "pH / Conductivity Meters", "AR / GR Grade Reagents", "Water & Soil Testing Kits", "HPLC & GC Systems", "Magnetic Stirrers & Ovens", "Refractometers", "Microbiology Consumables"],
  },
  {
    id: "beverage",
    title: "Food & Beverage Inputs",
    icon: "GlassWater",
    color: "from-rose-900 to-rose-800",
    products: ["Flavor Enhancers", "Fortification Blends", "Enzymes & Stabilizers", "Emulsifiers", "Anti-Caking Agents", "Dairy Processing Chemicals", "Beverage Additives", "Functional Ingredients"],
  },
];

export interface Product {
  slug: string;
  name: string;
  divisionId: string;
  image: string;
  tagline: string;
  description: string;
  applications: string[];
  grades: string[];
  packaging: string[];
  casNumber?: string;
}

export const PRODUCTS: Product[] = [
  /* ── Industrial Chemicals ── */
  {
    slug: "caustic-soda",
    name: "Caustic Soda",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/5988340/pexels-photo-5988340.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "High-purity sodium hydroxide in flakes and pearl form",
    description: "Caustic Soda (Sodium Hydroxide / NaOH) is one of the most widely used industrial alkalis. Orbitron supplies food-grade and technical-grade caustic soda in both flake and pearl forms, sourced from ISO-certified manufacturers. Used extensively in soap manufacturing, water treatment, textile processing, and pulp & paper industries across East Africa.",
    applications: ["Soap & detergent manufacturing", "Water treatment & pH adjustment", "Textile & leather processing", "Pulp & paper production", "Food processing (food grade)", "Chemical synthesis"],
    grades: ["Technical Grade", "Food Grade"],
    packaging: ["25 kg bags", "50 kg bags", "1,000 kg jumbo bags"],
    casNumber: "1310-73-2",
  },
  {
    slug: "sodium-hypochlorite",
    name: "Sodium Hypochlorite",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/8544931/pexels-photo-8544931.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Commercial-grade bleach for disinfection and water treatment",
    description: "Sodium Hypochlorite (NaOCl) is a powerful oxidising agent and disinfectant available in concentrations from 5% to 15%. Widely used for water purification, surface disinfection, laundry bleaching, and industrial cleaning. Orbitron supplies liquid sodium hypochlorite in bulk and drum quantities.",
    applications: ["Municipal water treatment", "Swimming pool sanitation", "Industrial disinfection", "Laundry & textile bleaching", "Food facility sanitation", "Effluent treatment"],
    grades: ["Commercial Grade 5–10%", "Industrial Grade 12–15%"],
    packaging: ["25 L jerricans", "200 L drums", "Bulk tanker"],
    casNumber: "7681-52-9",
  },
  {
    slug: "hydrochloric-acid",
    name: "Hydrochloric Acid",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/9628834/pexels-photo-9628834.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Industrial and food-grade HCl for a wide range of applications",
    description: "Hydrochloric Acid (HCl) is a strong mineral acid available in 30–37% concentration. Orbitron supplies both technical and food-grade hydrochloric acid for steel pickling, pH regulation, food processing, and chemical manufacturing. Supplied with full SDS documentation and HAZMAT-compliant delivery.",
    applications: ["Steel pickling & metal treatment", "pH regulation & adjustment", "Food processing & gelatine production", "Leather tanning", "Chemical synthesis", "Swimming pool pH correction"],
    grades: ["Technical Grade 30–33%", "Food Grade 30–33%", "Industrial Grade 35–37%"],
    packaging: ["35 kg carboys", "250 kg drums", "Bulk IBC"],
    casNumber: "7647-01-0",
  },
  {
    slug: "sulfuric-acid",
    name: "Sulfuric Acid",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/8544943/pexels-photo-8544943.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Industrial sulphuric acid in multiple concentrations",
    description: "Sulfuric Acid (H₂SO₄) is the world's most widely produced industrial chemical. Available in concentrations from 93–98%, it is an essential raw material for fertiliser production, battery acid, metal processing, and chemical synthesis. Orbitron supplies H₂SO₄ with full HAZMAT logistics and safety documentation.",
    applications: ["Fertiliser & phosphate production", "Battery acid (lead-acid batteries)", "Metal refining & pickling", "Petroleum refining", "Chemical synthesis", "Water treatment"],
    grades: ["93% Technical", "96–98% Industrial"],
    packaging: ["250 kg drums", "Bulk IBC", "Bulk tanker"],
    casNumber: "7664-93-9",
  },
  {
    slug: "nitric-acid",
    name: "Nitric Acid",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/8544943/pexels-photo-8544943.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Concentrated nitric acid for metal treatment and synthesis",
    description: "Nitric Acid (HNO₃) is a highly corrosive strong acid available at 60–68% concentration. Used in metal etching, explosives manufacturing, fertiliser production, and analytical chemistry. Orbitron supplies with full HAZMAT compliance and temperature-controlled transport.",
    applications: ["Metal etching & engraving", "Nitrate fertiliser production", "Explosives & propellants", "Analytical chemistry", "Jewellery & precious metal refining", "Pharmaceutical intermediates"],
    grades: ["60% Technical", "68% Concentrated", "Fuming (98%)"],
    packaging: ["35 kg carboys", "250 kg drums", "Bulk IBC"],
    casNumber: "7697-37-2",
  },
  {
    slug: "ammonia-solution",
    name: "Ammonia Solution",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/8544949/pexels-photo-8544949.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Aqueous ammonia 25–30% for industrial and agricultural use",
    description: "Ammonia Solution (NH₃ aqueous) is available at 25–30% concentration for industrial and agricultural applications. Used in fertiliser production, refrigeration, cleaning agents, and chemical synthesis. Orbitron supplies with proper HAZMAT packaging and documentation.",
    applications: ["Fertiliser production (nitrogen source)", "Refrigeration systems", "Cleaning & degreasing agents", "pH adjustment in water treatment", "Chemical synthesis", "Textile processing"],
    grades: ["25% Technical", "28–30% Industrial"],
    packaging: ["25 L jerricans", "200 L drums", "Bulk IBC"],
    casNumber: "1336-21-6",
  },
  {
    slug: "sodium-silicate",
    name: "Sodium Silicate",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/8544931/pexels-photo-8544931.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Water glass for adhesives, cements, and industrial coatings",
    description: "Sodium Silicate (Na₂SiO₃), also known as water glass, is a versatile inorganic compound used as a binder, adhesive, cement, and fire retardant. Available in liquid (solution) and solid forms with various SiO₂:Na₂O ratios. Widely used in detergent manufacturing, paper processing, and construction.",
    applications: ["Detergent & soap manufacturing", "Paper & cardboard sizing", "Construction & fireproofing", "Adhesives & sealants", "Textile processing", "Metal casting"],
    grades: ["Liquid 35–40° Bé", "Neutral Ratio", "Alkaline Ratio"],
    packaging: ["25 kg bags (solid)", "250 kg drums (liquid)", "Bulk IBC (liquid)"],
    casNumber: "1344-09-8",
  },
  {
    slug: "industrial-ethanol",
    name: "Industrial Ethanol",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/4946707/pexels-photo-4946707.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Denatured and technical-grade ethanol for industrial use",
    description: "Industrial Ethanol (C₂H₅OH) at 95–99% concentration is used across manufacturing, cleaning, cosmetics, and chemical synthesis. Orbitron supplies both denatured and undenatured grades with appropriate excise documentation and KEBS compliance.",
    applications: ["Solvent for coatings & adhesives", "Cleaning & sanitisation", "Cosmetics & personal care", "Pharmaceutical manufacturing", "Fuel blending", "Chemical synthesis"],
    grades: ["95% Rectified", "99% Anhydrous", "Denatured (IDA)"],
    packaging: ["25 L jerricans", "200 L drums", "Bulk IBC"],
    casNumber: "64-17-5",
  },

  /* ── Food Processing Chemicals ── */
  {
    slug: "citric-acid",
    name: "Citric Acid",
    divisionId: "food",
    image: "https://images.pexels.com/photos/5988340/pexels-photo-5988340.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Food-grade citric acid for beverages, confectionery, and preservation",
    description: "Citric Acid (C₆H₈O₇) is the most widely used food acidulant globally, available in monohydrate and anhydrous forms. Orbitron supplies KEBS-approved, food-grade citric acid sourced from GMP-certified manufacturers. Used in beverages, confectionery, dairy, and as a natural preservative and pH regulator.",
    applications: ["Carbonated & non-carbonated beverages", "Confectionery & sweets", "Dairy products & cheese", "Jams & preserves", "Personal care & cosmetics", "Pharmaceutical tablet formulations"],
    grades: ["Food Grade (E330)", "USP Grade", "BP Grade"],
    packaging: ["25 kg bags", "500 kg big bags"],
    casNumber: "77-92-9",
  },
  {
    slug: "ascorbic-acid",
    name: "Ascorbic Acid (Vitamin C)",
    divisionId: "food",
    image: "https://images.pexels.com/photos/5988342/pexels-photo-5988342.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Food and pharma grade Vitamin C for fortification and preservation",
    description: "Ascorbic Acid (Vitamin C / C₆H₈O₆) is an essential antioxidant used in food fortification, pharmaceutical formulations, and as a natural preservative. Orbitron supplies fine and granular grades from certified manufacturers, with full quality documentation.",
    applications: ["Beverage & juice fortification", "Bakery & flour treatment", "Edible oil antioxidant", "Meat colour preservation", "Pharmaceutical vitamin supplements", "Cosmetics & skincare"],
    grades: ["Food Grade (E300)", "USP Grade", "BP Grade"],
    packaging: ["25 kg fibre drums", "25 kg bags"],
    casNumber: "50-81-7",
  },
  {
    slug: "sodium-benzoate",
    name: "Sodium Benzoate",
    divisionId: "food",
    image: "https://images.pexels.com/photos/8108249/pexels-photo-8108249.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Effective preservative for beverages, condiments, and sauces",
    description: "Sodium Benzoate (C₇H₅NaO₂) is a widely used antimicrobial food preservative effective in acidic products such as carbonated beverages, juices, sauces, and pickles. Orbitron supplies granular and powder grades meeting international food safety standards.",
    applications: ["Carbonated soft drinks", "Fruit juices & concentrates", "Condiments & sauces", "Pickles & vinegar products", "Pharmaceutical syrups", "Personal care products"],
    grades: ["Food Grade (E211)", "USP Grade"],
    packaging: ["25 kg bags", "50 kg drums"],
    casNumber: "532-32-1",
  },
  {
    slug: "potassium-sorbate",
    name: "Potassium Sorbate",
    divisionId: "food",
    image: "https://images.pexels.com/photos/8108249/pexels-photo-8108249.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Mould and yeast inhibitor for dairy, beverages, and bakery",
    description: "Potassium Sorbate (C₆H₇KO₂) is a safe, widely-accepted food preservative used to inhibit mould and yeast in a broad range of food products. It is highly effective in dairy, beverages, baked goods, and fermented products. Orbitron supplies granular and powder forms from GMP-certified sources.",
    applications: ["Dairy products (yoghurt, cheese, cream)", "Beverages & wine", "Bakery & bread products", "Dried fruits & vegetables", "Margarines & spreads", "Personal care formulations"],
    grades: ["Food Grade (E202)", "Granular", "Powder"],
    packaging: ["25 kg bags", "50 kg drums"],
    casNumber: "590-00-1",
  },
  {
    slug: "lactic-acid",
    name: "Lactic Acid",
    divisionId: "food",
    image: "https://images.pexels.com/photos/8544931/pexels-photo-8544931.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Natural organic acid for dairy, beverages, and meat processing",
    description: "Lactic Acid (C₃H₆O₃) is a naturally-occurring organic acid produced by fermentation. Available in 80–90% food-grade concentrations, it is used as an acidulant, flavour enhancer, and preservative in dairy, meat, beverages, and baked goods. Orbitron supplies L(+) and DL-forms from GMP-certified facilities.",
    applications: ["Dairy (yoghurt, cheese, butter)", "Meat curing & preservation", "Carbonated beverages", "Bread & bakery products", "Salad dressings & sauces", "Pharmaceutical & cosmetic pH adjustment"],
    grades: ["Food Grade 80%", "Food Grade 88%", "USP Grade"],
    packaging: ["25 kg jerricans", "250 kg drums"],
    casNumber: "50-21-5",
  },
  {
    slug: "calcium-propionate",
    name: "Calcium Propionate",
    divisionId: "food",
    image: "https://images.pexels.com/photos/5988342/pexels-photo-5988342.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Bread and bakery mould inhibitor approved worldwide",
    description: "Calcium Propionate (Ca(C₂H₅COO)₂) is the most commonly used preservative in bread and bakery products. It inhibits the growth of mould and rope bacteria, extending shelf life without affecting yeast activity. Orbitron supplies fine granular grade meeting all major food safety certifications.",
    applications: ["Bread & bakery products", "Pizza dough & tortillas", "Cakes & pastries", "Processed cheese", "Animal feed preservation", "Grain & silage preservation"],
    grades: ["Food Grade (E282)", "Feed Grade"],
    packaging: ["25 kg bags", "500 kg big bags"],
    casNumber: "4075-81-4",
  },
  {
    slug: "acetic-acid",
    name: "Acetic Acid (Food Grade)",
    divisionId: "food",
    image: "https://images.pexels.com/photos/9629683/pexels-photo-9629683.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Food-grade glacial acetic acid for vinegar, pickling, and sauces",
    description: "Acetic Acid (CH₃COOH) at 99–100% glacial grade is the backbone of the vinegar and condiment industry. Orbitron supplies food-grade and technical-grade acetic acid with full KEBS documentation. Used in pickling, sauces, mayonnaise production, and as a pH regulator.",
    applications: ["Vinegar & condiment production", "Pickling of vegetables & fruits", "Mayonnaise & salad dressings", "pH adjustment in food processing", "Textile & leather industry", "Chemical synthesis"],
    grades: ["Food Grade 99–100% (E260)", "Technical Grade"],
    packaging: ["35 kg carboys", "250 kg drums", "Bulk IBC"],
    casNumber: "64-19-7",
  },

  /* ── Pharmaceutical Raw Materials ── */
  {
    slug: "glycerin-pharma",
    name: "Glycerin (Pharma Grade)",
    divisionId: "pharma",
    image: "https://images.pexels.com/photos/7904419/pexels-photo-7904419.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "USP/BP glycerol for pharmaceutical and cosmetic formulations",
    description: "Pharmaceutical-grade Glycerin (Glycerol / C₃H₈O₃) at 99.5%+ purity is an essential excipient in liquid formulations, topical preparations, suppositories, and oral syrups. Orbitron supplies vegetable-derived USP and BP grades with full CoA and pharmacopoeial testing certificates.",
    applications: ["Oral syrups & suspensions", "Topical creams & ointments", "Suppositories", "Cough & throat syrups", "Cosmetic moisturisers & serums", "Dental preparations"],
    grades: ["USP Grade 99.5%", "BP Grade 99.5%", "Kosher/Halal certified"],
    packaging: ["25 kg jerricans", "250 kg drums", "Bulk IBC"],
    casNumber: "56-81-5",
  },
  {
    slug: "sorbitol-solution",
    name: "Sorbitol Solution",
    divisionId: "pharma",
    image: "https://images.pexels.com/photos/27515660/pexels-photo-27515660.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "70% sorbitol solution for pharmaceutical syrups and cosmetics",
    description: "Sorbitol Solution 70% (C₆H₁₄O₆) is a polyol used as a humectant, sweetener, and excipient in pharmaceutical syrups, oral care products, and cosmetics. Orbitron supplies USP and food-grade sorbitol solution sourced from GMP-certified manufacturers with full documentation.",
    applications: ["Pharmaceutical oral syrups", "Toothpaste & oral care products", "Diabetic-friendly food products", "Cosmetic formulations", "Cough preparations", "Laxative preparations"],
    grades: ["USP Grade 70%", "Food Grade 70%"],
    packaging: ["25 kg jerricans", "250 kg drums", "Bulk IBC"],
    casNumber: "50-70-4",
  },
  {
    slug: "liquid-glucose",
    name: "Liquid Glucose",
    divisionId: "pharma",
    image: "https://images.pexels.com/photos/7615560/pexels-photo-7615560.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Pharmaceutical and food grade glucose syrup",
    description: "Liquid Glucose (Glucose Syrup) is a purified concentrated aqueous solution of saccharides used as a pharmaceutical excipient, sweetener, and humectant. Orbitron supplies BP/food-grade liquid glucose with DE values suited to pharmaceutical and confectionery applications.",
    applications: ["Pharmaceutical tablet coating & syrup base", "Confectionery & sugar products", "Bakery products & caramel", "Sports & energy drinks", "IV glucose solutions (hospital grade)", "Cosmetic formulations"],
    grades: ["USP/BP Grade", "Food Grade", "High DE (63–68)"],
    packaging: ["25 kg jerricans", "250 kg drums", "Bulk IBC"],
    casNumber: "8029-43-4",
  },
  {
    slug: "ethanol-pharma",
    name: "Ethanol (Pharma Grade)",
    divisionId: "pharma",
    image: "https://images.pexels.com/photos/7904419/pexels-photo-7904419.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "USP/BP pharmaceutical ethanol for formulations and sterilisation",
    description: "Pharmaceutical-grade Ethanol (Absolute / Rectified) at 95–99.9% purity is used across formulation, extraction, sterilisation, and as a solvent base. Orbitron supplies both rectified (95%) and absolute (99.5%+) grades meeting USP, BP, and EP pharmacopoeial specifications.",
    applications: ["Tinctures & herbal extracts", "Topical antiseptic preparations", "Pharmaceutical solvent", "Tablet film coating", "Inhalation formulations", "Sterilisation of equipment"],
    grades: ["Rectified 95% USP/BP", "Absolute 99.5% USP/BP", "Dehydrated 99.9%"],
    packaging: ["5 L bottles", "25 L jerricans", "200 L drums"],
    casNumber: "64-17-5",
  },
  {
    slug: "microcrystalline-cellulose",
    name: "Microcrystalline Cellulose",
    divisionId: "pharma",
    image: "https://images.pexels.com/photos/5988340/pexels-photo-5988340.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "MCC excipient for tablet compression and capsule filling",
    description: "Microcrystalline Cellulose (MCC / C₆H₁₀O₅)n is the most widely used direct compression excipient in pharmaceutical tablet manufacturing. Orbitron supplies multiple grades (PH 101, PH 102, PH 200) from NF/BP-certified manufacturers, with full particle size and moisture documentation.",
    applications: ["Direct tablet compression", "Wet granulation binder", "Capsule filling diluent", "Pellet extrusion spheronisation", "Antacid formulations", "Nutraceutical tablets"],
    grades: ["PH 101 (NF/BP/EP)", "PH 102 (NF/BP/EP)", "PH 200 (NF/BP/EP)"],
    packaging: ["25 kg fibre drums", "25 kg bags"],
    casNumber: "9004-34-6",
  },
  {
    slug: "propylene-glycol",
    name: "Propylene Glycol",
    divisionId: "pharma",
    image: "https://images.pexels.com/photos/4946707/pexels-photo-4946707.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "USP-grade propylene glycol for pharmaceutical and food use",
    description: "Propylene Glycol (PG / C₃H₈O₂) is a versatile pharmaceutical and food-grade excipient and humectant. Used as a solvent, co-solvent, humectant, and preservative in oral, topical, and injectable formulations. Orbitron supplies USP and food-grade PG with full certificates.",
    applications: ["Oral pharmaceutical formulations", "Topical creams & ointments", "Injectable preparations (solvent)", "Food humectant & flavour carrier", "Cosmetics & personal care", "Electronic cigarette liquids"],
    grades: ["USP Grade 99.5%+", "Food Grade (E1520)", "Technical Grade"],
    packaging: ["25 kg jerricans", "250 kg drums", "Bulk IBC"],
    casNumber: "57-55-6",
  },

  /* ── Petroleum & Solvents ── */
  {
    slug: "toluene",
    name: "Toluene",
    divisionId: "petroleum",
    image: "https://images.pexels.com/photos/15509863/pexels-photo-15509863.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "High-purity aromatic solvent for paints, coatings, and synthesis",
    description: "Toluene (C₇H₈) is a clear aromatic hydrocarbon solvent widely used in paints, coatings, adhesives, rubber, and chemical synthesis. Orbitron supplies industrial-grade toluene with purity ≥99.5% and full technical documentation.",
    applications: ["Paints & surface coatings", "Adhesives & sealants", "Rubber & plastics manufacturing", "Chemical & pharmaceutical synthesis", "Printing inks", "Leather tanning"],
    grades: ["Industrial Grade ≥99.5%", "Technical Grade ≥99.0%"],
    packaging: ["200 L drums", "Bulk IBC", "Bulk tanker"],
    casNumber: "108-88-3",
  },
  {
    slug: "acetone",
    name: "Acetone",
    divisionId: "petroleum",
    image: "https://images.pexels.com/photos/8544931/pexels-photo-8544931.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Industrial acetone solvent for coatings, cleaning, and synthesis",
    description: "Acetone (C₃H₆O) is one of the most commonly used organic solvents, known for its excellent solvency for many substances and rapid evaporation. Orbitron supplies industrial and technical-grade acetone for use in coatings, electronics cleaning, pharmaceuticals, and chemical production.",
    applications: ["Paint & varnish removers", "Cosmetics (nail polish remover)", "Electronics cleaning", "Pharmaceutical solvent", "Resin & polymer production", "Laboratory solvent"],
    grades: ["Industrial Grade ≥99.5%", "ACS Reagent Grade"],
    packaging: ["25 L jerricans", "200 L drums", "Bulk IBC"],
    casNumber: "67-64-1",
  },
  {
    slug: "isopropyl-alcohol",
    name: "Isopropyl Alcohol (IPA)",
    divisionId: "petroleum",
    image: "https://images.pexels.com/photos/4946707/pexels-photo-4946707.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "70% and 99% IPA for sanitisation, electronics, and industrial cleaning",
    description: "Isopropyl Alcohol (2-Propanol / C₃H₈O) is a versatile solvent and disinfectant available at 70% and 99% concentrations. Widely used for surface disinfection, electronics cleaning, pharmaceuticals, and as a solvent carrier. Orbitron supplies both pharmaceutical and industrial grades.",
    applications: ["Surface & hand sanitisation (70%)", "Electronics & PCB cleaning", "Pharmaceutical formulations", "Paint & resin thinning", "Printing ink solvent", "Cosmetics & personal care"],
    grades: ["Pharmaceutical 99% USP", "Technical 99%", "Sanitiser Grade 70%"],
    packaging: ["5 L bottles", "25 L jerricans", "200 L drums", "Bulk IBC"],
    casNumber: "67-63-0",
  },
  {
    slug: "hexane",
    name: "Hexane",
    divisionId: "petroleum",
    image: "https://images.pexels.com/photos/15509863/pexels-photo-15509863.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Food and industrial grade hexane for extraction and cleaning",
    description: "Hexane (n-Hexane / C₆H₁₄) is a non-polar hydrocarbon solvent primarily used for edible oil extraction, adhesive formulations, and laboratory use. Orbitron supplies food-grade hexane for oil extraction and industrial grade for manufacturing applications.",
    applications: ["Edible oil extraction (soybean, sunflower)", "Adhesive & rubber formulations", "Pharmaceutical extraction", "Cleaning of electronic components", "Textile industry", "Analytical chemistry"],
    grades: ["Food Grade ≥95%", "Industrial Grade ≥95%", "ACS Reagent Grade"],
    packaging: ["200 L drums", "Bulk IBC", "Bulk tanker"],
    casNumber: "110-54-3",
  },
  {
    slug: "xylene",
    name: "Xylene",
    divisionId: "petroleum",
    image: "https://images.pexels.com/photos/8544931/pexels-photo-8544931.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Mixed xylene solvent for paints, rubber, and manufacturing",
    description: "Xylene (C₈H₁₀) is an aromatic hydrocarbon solvent available as mixed xylenes or individual isomers. Used extensively in paints, varnishes, adhesives, rubber manufacturing, and as a clearing agent in histology. Orbitron supplies mixed and individual isomers from verified sources.",
    applications: ["Paints, coatings & varnishes", "Adhesives & sealants", "Rubber manufacturing", "Histology clearing agent", "Chemical synthesis intermediate", "Printing inks"],
    grades: ["Mixed Xylene ≥98%", "para-Xylene ≥99%"],
    packaging: ["200 L drums", "Bulk IBC", "Bulk tanker"],
    casNumber: "1330-20-7",
  },

  /* ── Laboratory Equipment ── */
  {
    slug: "spectrophotometer",
    name: "UV-VIS Spectrophotometer",
    divisionId: "laboratory",
    image: "https://images.pexels.com/photos/8442637/pexels-photo-8442637.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Benchtop UV-visible spectrophotometers for analytical labs",
    description: "High-accuracy UV-VIS and visible spectrophotometers for absorbance, transmittance, and concentration measurements. Orbitron supplies single-beam and double-beam models from leading manufacturers, complete with analytical software, calibration standards, and full after-sales support.",
    applications: ["Environmental water & soil analysis", "Food & beverage quality control", "Pharmaceutical assay & dissolution", "Clinical chemistry", "Colour measurement", "Research & academic laboratories"],
    grades: ["Single-beam Visible", "Double-beam UV-VIS", "Micro-volume UV-VIS"],
    packaging: ["Benchtop unit with accessories", "Full calibration kit included"],
  },
  {
    slug: "ph-conductivity-meter",
    name: "pH & Conductivity Meters",
    divisionId: "laboratory",
    image: "https://images.pexels.com/photos/3735773/pexels-photo-3735773.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Benchtop and portable meters for pH, conductivity, TDS, and ORP",
    description: "Precision benchtop and portable pH, conductivity, TDS, and ORP meters for laboratory, field, and process applications. Orbitron supplies a wide range of instruments with automatic temperature compensation, multiple buffers, and GLP data management, backed by calibration and technical support.",
    applications: ["Water quality monitoring", "Food & beverage QC", "Pharmaceutical process control", "Soil analysis", "Environmental monitoring", "Chemical manufacturing"],
    grades: ["Portable Meter", "Benchtop Meter", "Multi-parameter Meter"],
    packaging: ["Instrument + electrodes + buffers", "Carrying case for portable"],
  },
  {
    slug: "ar-grade-reagents",
    name: "Analytical Reagents (AR/GR Grade)",
    divisionId: "laboratory",
    image: "https://images.pexels.com/photos/15509863/pexels-photo-15509863.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "High-purity laboratory chemicals for analytical and research use",
    description: "Orbitron supplies a comprehensive range of Analytical Reagent (AR) and Guaranteed Reagent (GR) grade chemicals for laboratory analysis, research, and quality control. All products carry manufacturer's CoA with trace metal and impurity profiles, sourced from certified manufacturers in Europe and Asia.",
    applications: ["Wet chemistry analysis", "HPLC mobile phase preparation", "Standard solution preparation", "Atomic absorption spectroscopy", "Titration & volumetric analysis", "Research & method development"],
    grades: ["AR Grade", "GR Grade", "HPLC Grade", "ACS Grade"],
    packaging: ["500 g, 1 kg, 2.5 kg, 5 kg bottles/drums"],
  },
  {
    slug: "water-testing-kits",
    name: "Water & Soil Testing Kits",
    divisionId: "laboratory",
    image: "https://images.pexels.com/photos/8325713/pexels-photo-8325713.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "BOD, COD, chlorine, heavy metal, and soil nutrient test kits",
    description: "Complete testing kits for water quality parameters (BOD, COD, chlorine, turbidity, hardness, pH, heavy metals) and soil nutrient analysis. Orbitron stocks test strips, colorimetric kits, and digital photometer sets suitable for field and laboratory use, compliant with KEBS and ISO standards.",
    applications: ["Municipal & borehole water testing", "Wastewater & effluent monitoring", "Swimming pool water management", "Soil nutrient & pH testing", "Industrial process water QC", "Environmental compliance testing"],
    grades: ["Field Test Strips", "Colorimetric Kits", "Photometer + Reagent Sets"],
    packaging: ["Kit boxes (various parameter sets)"],
  },
  {
    slug: "hplc-gc-systems",
    name: "HPLC & GC Systems",
    divisionId: "laboratory",
    image: "https://images.pexels.com/photos/8325948/pexels-photo-8325948.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "High-performance liquid and gas chromatography systems",
    description: "Orbitron supplies HPLC (High Performance Liquid Chromatography) and GC (Gas Chromatography) systems for pharmaceutical, food safety, environmental, and petrochemical analysis. Systems include isocratic and gradient HPLC, GC-FID, GC-TCD, and GC-MS configurations with full installation and training support.",
    applications: ["Pharmaceutical analysis & purity testing", "Food adulteration & pesticide detection", "Environmental contaminant analysis", "Petrochemical & oil quality testing", "Flavour & fragrance analysis", "Research & method validation"],
    grades: ["Isocratic HPLC", "Gradient HPLC", "GC-FID / GC-TCD", "GC-MS"],
    packaging: ["System + column + software + installation"],
  },
  {
    slug: "magnetic-stirrer",
    name: "Magnetic Stirrers & Hotplates",
    divisionId: "laboratory",
    image: "https://images.pexels.com/photos/10187634/pexels-photo-10187634.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Precision magnetic stirrers and hotplate stirrers for labs",
    description: "Laboratory magnetic stirrers and combined hotplate-stirrer units for accurate mixing and heating of solutions. Orbitron supplies models from basic economy to advanced digital hotplate stirrers with temperature probes, ceramic tops, and safety features for demanding lab environments.",
    applications: ["Solution preparation & dissolution", "Titration experiments", "Reaction mixing", "Culture media preparation", "Chemical synthesis", "Quality control in food & pharma labs"],
    grades: ["Basic Magnetic Stirrer", "Hotplate Stirrer", "Digital Hotplate Stirrer"],
    packaging: ["Boxed unit with accessories"],
  },
  {
    slug: "microbiology-consumables",
    name: "Microbiology Consumables",
    divisionId: "laboratory",
    image: "https://images.pexels.com/photos/3735699/pexels-photo-3735699.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Culture media, petri dishes, pipettes, and sterile consumables",
    description: "Comprehensive range of microbiology consumables including dehydrated culture media, ready-made agar plates, pipettes, petri dishes, centrifuge tubes, and sterile swabs. Orbitron supplies international brands for food microbiology, clinical testing, water analysis, and pharmaceutical QC laboratories.",
    applications: ["Food & beverage microbiology QC", "Water & environmental testing", "Clinical & medical testing", "Pharmaceutical sterility testing", "Research & academic labs", "Industrial hygiene testing"],
    grades: ["Dehydrated Culture Media", "Ready-pour Agar Plates", "Sterile Consumables"],
    packaging: ["Cartons (various pack sizes)"],
  },

  /* ── Food & Beverage Inputs ── */
  {
    slug: "flavor-enhancers",
    name: "Flavor Enhancers",
    divisionId: "beverage",
    image: "https://images.pexels.com/photos/5078582/pexels-photo-5078582.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Monosodium glutamate, IMP, GMP, and natural flavour compounds",
    description: "Orbitron supplies a range of flavour enhancers including Monosodium Glutamate (MSG), disodium inosinate (IMP), disodium guanylate (GMP), and their blends. Used to intensify savoury, umami, and sweet flavour profiles in soups, seasonings, snacks, and processed foods.",
    applications: ["Soups, broths & bouillons", "Seasonings & spice blends", "Snack foods & crisps", "Instant noodles & processed meals", "Sauces & condiments", "Meat processing"],
    grades: ["Food Grade MSG (E621)", "Food Grade IMP (E631)", "Food Grade GMP (E627)", "I+G Blend"],
    packaging: ["25 kg bags", "500 kg big bags"],
  },
  {
    slug: "food-emulsifiers",
    name: "Emulsifiers",
    divisionId: "beverage",
    image: "https://images.pexels.com/photos/18631419/pexels-photo-36423802.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Lecithin, mono-diglycerides, and DATEM for food production",
    description: "Food emulsifiers improve texture, extend shelf life, and enhance the mixing of immiscible ingredients. Orbitron supplies soya lecithin, sunflower lecithin, mono- and diglycerides of fatty acids (E471), DATEM (E472e), and polysorbates for bakery, dairy, chocolate, and margarine production.",
    applications: ["Bread, rolls & bakery products", "Chocolate & compound coatings", "Margarine & spreads", "Ice cream & frozen desserts", "Dairy beverages & creamers", "Instant beverage powders"],
    grades: ["Soya Lecithin (E322)", "Sunflower Lecithin", "E471 Mono-diglycerides", "DATEM (E472e)"],
    packaging: ["25 kg bags/drums", "200 kg drums"],
  },
  {
    slug: "food-enzymes",
    name: "Enzymes & Stabilisers",
    divisionId: "beverage",
    image: "https://images.pexels.com/photos/5532664/pexels-photo-36423802.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Amylase, protease, lipase, and hydrocolloid stabilisers",
    description: "Enzymes optimise fermentation, dough performance, juice clarification, and dairy processing. Stabilisers ensure consistent texture and shelf life. Orbitron supplies amylases, proteases, lipases, glucose isomerases, pectinases, and hydrocolloids (carrageenan, xanthan gum, guar gum) for food and beverage production.",
    applications: ["Bread & bakery enzyme systems", "Beer & brewing enzymes", "Juice clarification & processing", "Dairy texturisation", "Meat processing", "Beverage stabilisation"],
    grades: ["Baking Enzymes", "Brewing Enzymes", "Dairy Enzymes", "Beverage Stabilisers"],
    packaging: ["1 kg, 5 kg, 25 kg packs"],
  },
  {
    slug: "fortification-blends",
    name: "Fortification Blends",
    divisionId: "beverage",
    image: "https://images.pexels.com/photos/5078596/pexels-photo-5078596.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Custom vitamin and mineral premixes for food fortification",
    description: "Orbitron supplies vitamin and mineral premix blends for fortification of flour, edible oils, cereals, beverages, and processed foods in line with national and WHO/FAO fortification standards. Custom blends are available for specific nutritional targets, with full formulation support.",
    applications: ["Wheat & maize flour fortification", "Edible oil vitamin fortification", "Breakfast cereal fortification", "Beverage & juice enrichment", "Infant formula supplementation", "Salt iodisation compounds"],
    grades: ["Standard Premix", "Custom Blend", "WHO/FAO Compliant"],
    packaging: ["1 kg, 5 kg, 25 kg sealed bags"],
  },

  /* ── Sugar Refinery Chemicals ── */
  {
    slug: "phosphoric-acid",
    name: "Phosphoric Acid",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/8544949/pexels-photo-8544949.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Food and technical grade phosphoric acid for juice clarification and cleaning",
    description: "Phosphoric Acid (H₃PO₄) is a key process chemical in sugar refining, used for juice clarification, impurity removal, and scale cleaning. Also widely used in food & beverage pH adjustment, metal treatment, and fertiliser production. Orbitron supplies food-grade (85%) and technical-grade concentrations with full KEBS documentation.",
    applications: ["Sugar juice clarification & impurity removal", "pH adjustment in food & beverages", "Metal surface treatment & rust removal", "Fertiliser & phosphate salt production", "Scale and mineral deposit removal (CIP)", "Detergent and cleaning compound formulation"],
    grades: ["Food Grade 85% (E338)", "Technical Grade 85%", "Industrial Grade 75%"],
    packaging: ["35 kg carboys", "250 kg drums", "Bulk IBC"],
    casNumber: "7664-38-2",
  },
  {
    slug: "lime-calcium-hydroxide",
    name: "Lime (Calcium Hydroxide)",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/5988340/pexels-photo-5988340.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Hydrated lime for juice clarification, pH control, and water treatment",
    description: "Hydrated Lime (Calcium Hydroxide / Ca(OH)₂) is an essential process chemical in sugar refining for juice clarification, milk-of-lime preparation, and pH control. Also used in water treatment, construction, and flue gas desulphurisation. Orbitron supplies food-process and industrial grades in powder and slurry forms.",
    applications: ["Sugar juice clarification (defecation process)", "Milk-of-lime preparation for sugar mills", "Water treatment pH adjustment", "Flue gas & effluent neutralisation", "Construction & soil stabilisation", "Leather processing"],
    grades: ["Food Process Grade", "Industrial Grade 90%+", "Technical Grade"],
    packaging: ["25 kg bags", "50 kg bags", "1,000 kg jumbo bags"],
    casNumber: "1305-62-0",
  },
  {
    slug: "activated-carbon",
    name: "Activated Carbon",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/6331084/pexels-photo-6331084.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Granular and powdered activated carbon for decolourisation and purification",
    description: "Activated Carbon (Activated Charcoal) is a highly porous adsorbent used for decolourisation, taste & odour removal, and impurity adsorption in sugar refining, water treatment, and food processing. Orbitron supplies both Granular Activated Carbon (GAC) and Powdered Activated Carbon (PAC) from wood, coal, and coconut shell sources.",
    applications: ["Sugar syrup decolourisation & colour removal", "Drinking water taste & odour removal", "Food & beverage decolourisation", "Pharmaceutical purification", "Wastewater & effluent treatment", "Gold recovery & precious metals"],
    grades: ["Powdered AC (sugar grade)", "Granular AC (water grade)", "Food Grade (EP/USP)"],
    packaging: ["25 kg bags", "500 kg big bags", "Bulk"],
    casNumber: "7440-44-0",
  },
  {
    slug: "flocculants-polyacrylamide",
    name: "Flocculants & Polyacrylamide",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/5123347/pexels-photo-5123347.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Anionic, cationic, and non-ionic flocculants for clarification and settling",
    description: "Polyacrylamide-based flocculants are used to accelerate settling of suspended solids in sugar juice clarification, wastewater treatment, and mineral processing. Orbitron supplies anionic, cationic, and non-ionic grades in powder and emulsion form, with technical support for dosage optimisation.",
    applications: ["Sugar juice clarification & settling", "Wastewater & effluent treatment", "Municipal water treatment", "Mineral processing & mining", "Paper & pulp processing", "Sludge dewatering"],
    grades: ["Anionic PAM", "Cationic PAM", "Non-ionic PAM", "Anionic Polyelectrolyte"],
    packaging: ["25 kg bags", "200 kg drums (emulsion)"],
    casNumber: "9003-05-8",
  },
  {
    slug: "hydrogen-peroxide",
    name: "Hydrogen Peroxide",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/8544949/pexels-photo-8544949.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "35–50% hydrogen peroxide for bleaching, sanitation, and colour correction",
    description: "Hydrogen Peroxide (H₂O₂) is a powerful oxidising agent and bleach used in sugar colour correction, surface sanitation, textile bleaching, and wastewater treatment. Orbitron supplies 35% and 50% concentrations with full HAZMAT packaging and technical support.",
    applications: ["Sugar colour correction & bleaching", "Surface and equipment sanitation (food industry)", "Textile & paper bleaching", "Wastewater treatment & oxidation", "Pharmaceutical disinfection", "Electronics and PCB cleaning"],
    grades: ["Food Grade 35%", "Technical Grade 35%", "Industrial Grade 50%"],
    packaging: ["25 kg jerricans", "250 kg drums", "Bulk IBC"],
    casNumber: "7722-84-1",
  },
  {
    slug: "aluminium-sulfate-alum",
    name: "Aluminium Sulfate (Alum)",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/5988340/pexels-photo-5988340.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Water treatment coagulant for drinking water and industrial clarification",
    description: "Aluminium Sulfate (Al₂(SO₄)₃·18H₂O) — commonly known as Alum — is the most widely used coagulant in water treatment and sugar processing. It destabilises colloidal particles, enabling rapid settling and filtration. Orbitron supplies granular and liquid grades for municipal water works, sugar factories, and industrial effluent plants.",
    applications: ["Municipal & industrial water clarification", "Sugar factory water treatment", "Wastewater & effluent treatment", "Paper & pulp sizing agent", "Swimming pool water treatment", "Dyestuff fixation in textiles"],
    grades: ["Water Treatment Grade 17%", "Technical Grade", "Liquid Alum 8%"],
    packaging: ["25 kg bags", "50 kg bags", "Bulk IBC (liquid)"],
    casNumber: "10043-01-3",
  },
  {
    slug: "polyaluminium-chloride",
    name: "Polyaluminium Chloride (PAC)",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/5115943/pexels-photo-5115943.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "High-performance PAC coagulant for water and wastewater treatment",
    description: "Polyaluminium Chloride (PAC) is a superior coagulant to alum, effective across a wider pH range and producing less sludge. Used in drinking water treatment, industrial process water, sugar factory clarification, and wastewater management. Orbitron supplies liquid and powder PAC with Al₂O₃ content from 10–30%.",
    applications: ["Drinking water clarification", "Sugar refinery process water", "Industrial wastewater treatment", "Paper & pulp manufacturing", "Textile effluent treatment", "Sludge dewatering"],
    grades: ["Liquid PAC 10% Al₂O₃", "Liquid PAC 17% Al₂O₃", "Powder PAC 30% Al₂O₃"],
    packaging: ["25 kg bags (powder)", "1,000 L IBC (liquid)", "Bulk tanker"],
    casNumber: "1327-41-9",
  },
  {
    slug: "antiscalants-corrosion-inhibitors",
    name: "Antiscalants & Corrosion Inhibitors",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/5123343/pexels-photo-5123343.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Scale and corrosion control for boilers, cooling towers, and process equipment",
    description: "Antiscalants prevent scale deposition on heat transfer surfaces, pipework, and membranes in boilers, cooling towers, RO systems, and evaporators. Corrosion inhibitors protect metal surfaces from oxidative and acid attack. Orbitron supplies phosphonate, polymer, and molybdate-based formulations tailored for sugar factory and industrial water systems.",
    applications: ["Boiler scale prevention & deposit control", "Cooling tower scale & corrosion control", "RO membrane antiscalant", "Sugar factory evaporator scale prevention", "Heat exchanger protection", "Open & closed recirculating water systems"],
    grades: ["Boiler Antiscalant", "Cooling Tower Antiscalant", "RO Membrane Antiscalant", "Corrosion Inhibitor"],
    packaging: ["25 L jerricans", "200 L drums", "IBC"],
  },
  {
    slug: "sodium-sulfite",
    name: "Sodium Sulfite",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/5988340/pexels-photo-5988340.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Oxygen scavenger and reducing agent for boiler water treatment",
    description: "Sodium Sulfite (Na₂SO₃) is used as an oxygen scavenger in boiler water treatment to prevent corrosion from dissolved oxygen. Also used as a preservative, reducing agent in photographic processing, and in the paper industry. Orbitron supplies anhydrous and heptahydrate grades with technical support for boiler chemistry programmes.",
    applications: ["Boiler water oxygen scavenging", "Corrosion prevention in steam systems", "Food preservation (E221)", "Photographic chemical processing", "Paper pulp bleaching & processing", "Dechlorination of water"],
    grades: ["Technical Grade Anhydrous", "Food Grade (E221)", "Heptahydrate Grade"],
    packaging: ["25 kg bags", "50 kg drums"],
    casNumber: "7757-83-7",
  },
  {
    slug: "peracetic-acid",
    name: "Peracetic Acid",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/8544949/pexels-photo-8544949.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Low-residue sanitiser for CIP, food processing, and water treatment",
    description: "Peracetic Acid (PAA / CH₃CO₃H) is a highly effective, fast-acting antimicrobial agent that leaves no harmful residues, making it ideal for food processing sanitation, CIP (Clean-in-Place) systems, and membrane disinfection. Orbitron supplies 5–15% PAA solutions for food industry and water treatment applications.",
    applications: ["CIP (Clean-in-Place) sanitisation in food factories", "Sugar mill & beverage plant disinfection", "Membrane & RO system disinfection", "Poultry & meat processing sanitation", "Brewery & winery sanitation", "Healthcare surface disinfection"],
    grades: ["Food Grade 5%", "Food Grade 15%", "Industrial Grade 15%"],
    packaging: ["25 L jerricans", "200 L drums"],
    casNumber: "79-21-0",
  },
  {
    slug: "ferric-chloride",
    name: "Ferric Chloride",
    divisionId: "industrial",
    image: "https://images.pexels.com/photos/8544943/pexels-photo-8544943.jpeg?auto=compress&cs=tinysrgb&w=800",
    tagline: "Effective coagulant for water clarification and wastewater treatment",
    description: "Ferric Chloride (FeCl₃) is a highly effective coagulant for water and wastewater treatment, producing a dense, fast-settling floc. Used in municipal water works, industrial effluent treatment, and phosphate removal. Orbitron supplies both liquid (40%) and anhydrous powder grades.",
    applications: ["Municipal water clarification & treatment", "Industrial wastewater & effluent treatment", "Phosphate removal from water", "Sugar factory process water treatment", "PCB etching (electronics)", "Sludge conditioning & dewatering"],
    grades: ["Liquid 40% (Water Treatment Grade)", "Anhydrous Powder Technical Grade"],
    packaging: ["25 kg bags (powder)", "250 kg drums (liquid)", "Bulk IBC"],
    casNumber: "7705-08-0",
  },
];

export const INDUSTRIES = [
  { slug: "manufacturing",    title: "Manufacturing",              tag: "Industrial Chemicals",    img: "https://images.pexels.com/photos/6837596/pexels-photo-6837596.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { slug: "sugar-refinery",   title: "Sugar Refinery",            tag: "Process Chemicals",       img: "https://images.pexels.com/photos/7457175/pexels-photo-7457175.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { slug: "food-beverage",    title: "Food & Beverage",           tag: "Food Additives",          img: "https://images.pexels.com/photos/36423812/pexels-photo-36423812.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { slug: "pharmaceuticals",  title: "Pharmaceuticals",           tag: "Pharma Grade",            img: "https://images.pexels.com/photos/37650270/pexels-photo-37650270.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { slug: "water-treatment",  title: "Water Treatment",           tag: "Water Chemicals",         img: "https://images.pexels.com/photos/36926327/pexels-photo-36926327.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { slug: "petroleum-energy", title: "Petroleum & Energy",        tag: "Petroleum Chemicals",     img: "https://images.pexels.com/photos/4883682/pexels-photo-4883682.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { slug: "laboratories",     title: "Research Laboratories",     tag: "Lab Equipment",           img: "https://images.pexels.com/photos/9243545/pexels-photo-9243545.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { slug: "agriculture",      title: "Agriculture",               tag: "Agro-Chemicals",          img: "https://images.pexels.com/photos/30255157/pexels-photo-30255157.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { slug: "government",       title: "Government & Institutions", tag: "Institutional Supply",    img: "https://images.pexels.com/photos/18658526/pexels-photo-18658526.jpeg?auto=compress&cs=tinysrgb&w=600" },
];

export interface IndustryContent {
  slug: string;
  heroHeadline: string;
  overview: string;
  chemicals: { category: string; items: string[] }[];
  whyOrbitron: string[];
  relatedProducts: string[];
  seoKeywords: string[];
}

export const INDUSTRY_CONTENT: Record<string, IndustryContent> = {
  manufacturing: {
    slug: "manufacturing",
    heroHeadline: "Industrial Chemicals for Manufacturing",
    overview: "East Africa's manufacturing sector demands consistent, high-quality industrial chemicals for process operations, cleaning, pH control, and surface treatment. Orbitron Sciechem is the region's trusted single-source supplier for manufacturing inputs — from caustic soda and sulfuric acid to specialty solvents and process aids.",
    chemicals: [
      { category: "Process & Reaction Chemicals", items: ["Caustic Soda (NaOH)", "Sulfuric Acid", "Hydrochloric Acid", "Nitric Acid", "Ammonia Solution", "Sodium Silicate"] },
      { category: "Solvents & Degreasers", items: ["Industrial Ethanol", "Isopropyl Alcohol", "Acetone", "Toluene", "Xylene", "White Spirit"] },
      { category: "Cleaning & CIP", items: ["Caustic Soda", "Nitric Acid", "Phosphoric Acid", "Peracetic Acid", "Sodium Hypochlorite"] },
    ],
    whyOrbitron: ["Buffer stock maintained for fast-moving industrial chemicals", "Bulk and drum packaging for high-volume manufacturing", "HAZMAT-compliant delivery to factory gates across East Africa", "Technical process support and troubleshooting", "KEBS and ISO certified products with full documentation"],
    relatedProducts: ["caustic-soda", "sulfuric-acid", "hydrochloric-acid", "sodium-hypochlorite", "industrial-ethanol", "toluene"],
    seoKeywords: ["industrial chemicals manufacturer Kenya", "caustic soda supplier Kenya", "sulfuric acid Kenya"],
  },
  "food-beverage": {
    slug: "food-beverage",
    heroHeadline: "Food-Grade Ingredients & Additives for Food & Beverage Producers",
    overview: "From citric acid and preservatives to emulsifiers, enzymes, and fortification blends — Orbitron Sciechem supplies the full range of food-grade chemical inputs needed by beverage manufacturers, bakeries, dairy processors, and food factories across Kenya and East Africa.",
    chemicals: [
      { category: "Acidulants & pH Regulators", items: ["Citric Acid Monohydrate", "Lactic Acid", "Acetic Acid (Food Grade)", "Phosphoric Acid (Food Grade)"] },
      { category: "Preservatives & Antimicrobials", items: ["Sodium Benzoate", "Potassium Sorbate", "Calcium Propionate", "Sodium Metabisulfite"] },
      { category: "Vitamins & Fortification", items: ["Ascorbic Acid (Vitamin C)", "Vitamin AD3", "Fortification Blends", "Zinc Oxide"] },
      { category: "Functional Ingredients", items: ["Flavor Enhancers (MSG, I+G)", "Emulsifiers (Lecithin, E471)", "Enzymes & Stabilisers", "Anti-Caking Agents"] },
    ],
    whyOrbitron: ["All products KEBS, ISO, HACCP and food-grade certified", "E-number documentation and regulatory compliance", "Halal and Kosher certified options available", "Consistent supply for beverage, bakery, dairy and meat processing", "Technical formulation support for new product development"],
    relatedProducts: ["citric-acid", "ascorbic-acid", "sodium-benzoate", "potassium-sorbate", "calcium-propionate", "acetic-acid"],
    seoKeywords: ["food ingredients supplier Kenya", "citric acid Kenya", "food preservatives East Africa"],
  },
  pharmaceuticals: {
    slug: "pharmaceuticals",
    heroHeadline: "GMP-Certified Pharmaceutical Raw Materials",
    overview: "Pharmaceutical manufacturers across Kenya and East Africa rely on Orbitron Sciechem for USP, BP, and EP grade excipients, solvents, and APIs. Every product is supplied with full Certificates of Analysis, Safety Data Sheets, and regulatory documentation.",
    chemicals: [
      { category: "Excipients & Carriers", items: ["Microcrystalline Cellulose (MCC)", "Glycerin (Pharma Grade)", "Sorbitol Solution 70%", "Liquid Glucose", "Propylene Glycol"] },
      { category: "Solvents & Diluents", items: ["Ethanol (Pharma Grade 95% / Absolute)", "Isopropyl Alcohol (USP)", "Propylene Glycol"] },
      { category: "Acids & Alkalis (BP Grade)", items: ["Hydrochloric Acid (BP)", "Sodium Hydroxide (BP)", "Phosphoric Acid (BP)", "Citric Acid (BP)"] },
    ],
    whyOrbitron: ["USP, BP, EP and pharmacopoeial grade products available", "Full Certificate of Analysis (CoA) and SDS with every batch", "GMP-compliant sourcing and quality management", "Temperature-controlled storage and transport", "Regulatory compliance for KEBS and national drug authorities"],
    relatedProducts: ["glycerin-pharma", "sorbitol-solution", "liquid-glucose", "ethanol-pharma", "microcrystalline-cellulose", "propylene-glycol"],
    seoKeywords: ["pharmaceutical raw materials Kenya", "pharma excipients supplier Kenya", "GMP chemicals East Africa"],
  },
  "water-treatment": {
    slug: "water-treatment",
    heroHeadline: "Water Treatment Chemicals for Municipal & Industrial Applications",
    overview: "Orbitron Sciechem supplies the complete range of water and wastewater treatment chemicals to municipal utilities, industrial process water plants, and effluent treatment facilities across Kenya, Uganda, Tanzania and beyond.",
    chemicals: [
      { category: "Coagulants & Flocculants", items: ["Aluminium Sulfate (Alum)", "Polyaluminium Chloride (PAC)", "Ferric Chloride", "Polyacrylamide Flocculant"] },
      { category: "Disinfection", items: ["Sodium Hypochlorite (5–15%)", "Calcium Hypochlorite", "Sodium Dichloroisocyanurate"] },
      { category: "pH Adjustment", items: ["Lime (Calcium Hydroxide)", "Caustic Soda", "Sulfuric Acid", "Carbon Dioxide"] },
      { category: "Scale & Corrosion Control", items: ["Antiscalants", "Corrosion Inhibitors", "Sodium Sulfite (Oxygen Scavenger)"] },
    ],
    whyOrbitron: ["Bulk tanker delivery for liquid chemicals to treatment plants", "Technical dosing support for coagulation and disinfection", "KEBS compliant products for municipal water supply", "Same-day dispatch for critical shortages", "Serving Nairobi Water, county utilities and industrial effluent plants"],
    relatedProducts: ["aluminium-sulfate-alum", "polyaluminium-chloride", "ferric-chloride", "sodium-hypochlorite", "flocculants-polyacrylamide", "antiscalants-corrosion-inhibitors"],
    seoKeywords: ["water treatment chemicals Kenya", "alum supplier Kenya", "PAC chemical East Africa", "sodium hypochlorite water treatment"],
  },
  "petroleum-energy": {
    slug: "petroleum-energy",
    heroHeadline: "Petroleum Solvents, Lubricant Additives & Energy Chemicals",
    overview: "The petroleum and energy sector requires high-purity aromatic solvents, aliphatic hydrocarbons, lubricant additives, and specialty chemicals for refining, blending, and maintenance. Orbitron Sciechem supplies these from verified sources with full technical documentation.",
    chemicals: [
      { category: "Aromatic Solvents", items: ["Toluene", "Xylene (mixed / para)", "Solvent Naphtha", "Benzene (industrial)"] },
      { category: "Aliphatic Solvents", items: ["Hexane", "White Spirit", "Mineral Turpentine"] },
      { category: "Lubricant Additives & Specialty", items: ["Lubricant Additives", "Viscosity Index Improvers", "Antiwear Additives", "Corrosion Inhibitors"] },
      { category: "Cleaning & Degreasing", items: ["Acetone", "Isopropyl Alcohol", "Methyl Ethyl Ketone (MEK)"] },
    ],
    whyOrbitron: ["Bulk tanker supply for high-volume petroleum chemical requirements", "Flash point, SDS and specifications for all solvents", "HAZMAT certified logistics for dangerous goods", "Serving oil marketing companies, refineries, and blending plants", "Technical data sheets for all products"],
    relatedProducts: ["toluene", "xylene", "hexane", "acetone", "isopropyl-alcohol", "antiscalants-corrosion-inhibitors"],
    seoKeywords: ["petroleum chemicals Kenya", "toluene supplier East Africa", "solvent supplier Kenya", "lubricant additives Kenya"],
  },
  laboratories: {
    slug: "laboratories",
    heroHeadline: "Laboratory Equipment, Reagents & Analytical Solutions",
    overview: "From universities and research institutions to hospital labs and industrial QC facilities — Orbitron Sciechem supplies a comprehensive range of laboratory instruments, analytical reagents, consumables, and testing kits to support scientific work across East Africa.",
    chemicals: [
      { category: "Analytical Instruments", items: ["UV-VIS Spectrophotometers", "pH & Conductivity Meters", "HPLC & GC Systems", "Refractometers", "Magnetic Stirrers"] },
      { category: "Reagents & Standards", items: ["AR / GR Grade Reagents", "HPLC Mobile Phase Solvents", "Titration Standards", "Buffer Solutions"] },
      { category: "Testing Kits", items: ["Water Testing Kits (BOD, COD, Chlorine)", "Soil Testing Kits", "Heavy Metal Test Kits", "Microbiology Media"] },
      { category: "Consumables", items: ["Petri Dishes", "Test Tubes & Flasks", "Pipettes & Tips", "Centrifuge Tubes", "Filter Papers"] },
    ],
    whyOrbitron: ["Full after-sales support, calibration services and warranty", "Same-day dispatch for common consumables from Nairobi warehouse", "50+ instrument brands stocked", "Installation, training and technical support from certified engineers", "Certificates of Analysis for all analytical reagents"],
    relatedProducts: ["spectrophotometer", "ph-conductivity-meter", "ar-grade-reagents", "water-testing-kits", "hplc-gc-systems", "microbiology-consumables"],
    seoKeywords: ["laboratory equipment Kenya", "lab reagents supplier Kenya", "spectrophotometer Kenya", "HPLC system East Africa"],
  },
  agriculture: {
    slug: "agriculture",
    heroHeadline: "Agricultural Chemicals, Fertiliser Inputs & Soil Testing Solutions",
    overview: "Kenya's agricultural sector requires quality soil amendments, fertiliser raw materials, crop protection chemical inputs, and precision testing tools. Orbitron Sciechem supplies these inputs with technical advisory support and nationwide delivery.",
    chemicals: [
      { category: "Fertiliser Raw Materials", items: ["Calcium Nitrate", "Potassium Nitrate", "Phosphoric Acid (Fertiliser Grade)", "Urea", "Ammonium Sulfate"] },
      { category: "Soil Amendments", items: ["Lime (Calcium Hydroxide)", "Gypsum (Calcium Sulfate)", "Humic Acid", "Micronutrient Blends"] },
      { category: "Crop Protection Support", items: ["Surfactants & Adjuvants", "Emulsifiers", "pH Buffering Agents"] },
      { category: "Testing & Analysis", items: ["Soil Testing Kits", "Water Testing Kits", "pH Meters", "Conductivity Meters"] },
    ],
    whyOrbitron: ["Agronomic technical support for soil chemistry and fertiliser programmes", "Upcountry delivery across Kenya", "Bulk supply for large-scale commercial farms", "Precision agriculture testing solutions", "Competitive pricing for seasonal high-volume inputs"],
    relatedProducts: ["lime-calcium-hydroxide", "phosphoric-acid", "water-testing-kits", "ph-conductivity-meter", "aluminium-sulfate-alum"],
    seoKeywords: ["agricultural chemicals Kenya", "fertiliser inputs Kenya", "soil testing kits Kenya", "agro-chemicals East Africa"],
  },
  government: {
    slug: "government",
    heroHeadline: "Bulk Chemical & Laboratory Supply for Government & Public Institutions",
    overview: "Government ministries, parastatals, public universities, hospitals and county governments across Kenya trust Orbitron Sciechem for bulk chemical and laboratory supply. We support procurement teams with LPO-based purchasing, framework agreements, and volume pricing.",
    chemicals: [
      { category: "Water & Sanitation", items: ["Sodium Hypochlorite", "Calcium Hypochlorite", "Alum", "PAC", "Lime"] },
      { category: "Laboratory & Research", items: ["Analytical Reagents (AR Grade)", "Laboratory Equipment", "Testing Kits", "Consumables"] },
      { category: "Industrial & Maintenance", items: ["Caustic Soda", "Hydrochloric Acid", "Solvents & Degreasers"] },
      { category: "Healthcare & Sanitation", items: ["Hydrogen Peroxide", "Isopropyl Alcohol (70%)", "Peracetic Acid", "Sodium Hypochlorite (Dilute)"] },
    ],
    whyOrbitron: ["LPO and framework agreement procurement supported", "Volume discounts for institutional bulk purchases", "Full tender documentation and compliance certificates", "Delivery to depots, hospitals and institutions countrywide", "Registered supplier with Kenya government procurement systems"],
    relatedProducts: ["sodium-hypochlorite", "aluminium-sulfate-alum", "caustic-soda", "hydrogen-peroxide", "ar-grade-reagents"],
    seoKeywords: ["chemical supplier government Kenya", "laboratory supply government institutions Kenya", "bulk chemicals public sector Kenya"],
  },
};

export const WHY_CHOOSE = [
  {
    title: "Certified Products",
    desc: "All products meet KEBS, ISO, and GMP standards. We supply only verified, quality-assured chemicals and laboratory solutions.",
    icon: "Trophy",
  },
  {
    title: "Global Partnerships",
    desc: "Direct sourcing from 50+ leading manufacturers across Europe, North America, and Asia ensures premium quality and competitive pricing.",
    icon: "Globe",
  },
  {
    title: "Technical Expertise",
    desc: "Our team of industry specialists and laboratory experts provides hands-on technical guidance and application support.",
    icon: "Microscope",
  },
  {
    title: "Reliable Supply",
    desc: "Consistent inventory levels, buffer stock management, and just-in-time delivery minimize disruption to your operations.",
    icon: "PackageCheck",
  },
  {
    title: "Customer-Centric",
    desc: "We work as a long-term strategic partner — tailoring product recommendations, formulations, and logistics to your needs.",
    icon: "Handshake",
  },
  {
    title: "Regional Reach",
    desc: "Distribution spanning Kenya, Uganda, Tanzania, Rwanda, Ethiopia, and South Sudan with reliable last-mile delivery.",
    icon: "MapPin",
  },
];

export const PROCESS_STEPS = [
  { num: "01", title: "Consultation",       desc: "Discuss your requirements, industry needs, and technical specifications with our specialists." },
  { num: "02", title: "Product Selection",  desc: "We identify and recommend optimal products from our 1,000+ catalog tailored to your application." },
  { num: "03", title: "Quality Verification", desc: "Every batch undergoes rigorous quality checks — COA and compliance documents provided." },
  { num: "04", title: "Order Fulfillment",  desc: "Efficient processing, secure packaging, and timely delivery to your facility across East Africa." },
  { num: "05", title: "Technical Support",  desc: "Ongoing after-sales support, application guidance, and reorder management by our dedicated team." },
];

export const TESTIMONIALS = [
  {
    quote: "Orbitron Sciechem has consistently supplied us with high-quality industrial chemicals with reliable delivery timelines. Their technical team is always available for guidance and support.",
    name: "James Muthoni",
    role: "Head of Procurement",
    company: "East Africa Packaging Ltd.",
    industry: "Manufacturing",
  },
  {
    quote: "Their laboratory solutions have significantly improved our testing capabilities. The equipment quality is exceptional and after-sales support has been outstanding.",
    name: "Dr. Amina Hassan",
    role: "Laboratory Director",
    company: "Kenya Medical Research Centre",
    industry: "Research & Laboratory",
  },
  {
    quote: "Orbitron Sciechem has become our sole-source supplier for food-grade ingredients. Their product range and competitive pricing are unmatched in East Africa.",
    name: "Peter Kariuki",
    role: "Operations Manager",
    company: "Savannah Beverages Ltd.",
    industry: "Food & Beverage",
  },
  {
    quote: "As a pharmaceutical manufacturer, quality and compliance are non-negotiable. Orbitron delivers pharma-grade raw materials with full documentation — COAs, MSDS, and regulatory certificates — every time.",
    name: "Dr. Grace Wanjiku",
    role: "Quality Assurance Manager",
    company: "Medivet Pharmaceuticals",
    industry: "Pharmaceuticals",
  },
  {
    quote: "Our water treatment plant relies on Orbitron Sciechem for all purification chemicals. Their consistent supply, competitive pricing, and technical expertise make them an invaluable partner.",
    name: "Samuel Odhiambo",
    role: "Plant Manager",
    company: "Nairobi Water Company",
    industry: "Water Treatment",
  },
  {
    quote: "Sourcing petroleum solvents has never been easier. Orbitron maintains excellent stock levels and their logistics team ensures on-schedule delivery every time.",
    name: "Fatuma Ali",
    role: "Supply Chain Director",
    company: "Total Petroleum Kenya",
    industry: "Petroleum & Energy",
  },
];

export const CONTACT = {
  phone: "+254 742 651 823",
  email: "info@orbitronsciechem.com",
  address: "Hillpark Business Park, Go-Down 4, Nairobi, Kenya",
  hours: {
    weekdays: "Monday–Friday: 8:00 AM – 6:00 PM",
    saturday: "Saturday: 9:00 AM – 2:00 PM",
  },
  countries: ["KE", "UG", "TZ", "RW", "ET", "SS"],
};

export const NAV_PRODUCTS = [
  { label: "Industrial Chemicals",         href: "/products#industrial" },
  { label: "Food Processing Chemicals",    href: "/products#food" },
  { label: "Pharmaceutical Raw Materials", href: "/products#pharma" },
  { label: "Petroleum & Solvents",         href: "/products#petroleum" },
  { label: "Laboratory Equipment",         href: "/products#laboratory" },
  { label: "Food & Beverage Inputs",       href: "/products#beverage" },
];

export const NAV_INDUSTRIES = [
  { label: "Manufacturing",           href: "/industries/manufacturing" },
  { label: "Sugar Refinery",          href: "/industries/sugar-refinery" },
  { label: "Food & Beverage",         href: "/industries/food-beverage" },
  { label: "Pharmaceuticals",         href: "/industries/pharmaceuticals" },
  { label: "Water Treatment",         href: "/industries/water-treatment" },
  { label: "Petroleum & Energy",      href: "/industries/petroleum-energy" },
  { label: "Research Laboratories",   href: "/industries/laboratories" },
  { label: "Agriculture",             href: "/industries/agriculture" },
  { label: "Government & Institutions", href: "/industries/government" },
];
